spring.datasource:
  url: jdbc:mysql://localhost:3306/reactive?characterEncoding=UTF-8&useSSL=false
  username: root
  password: anywhere
  driverClassName: com.mysql.jdbc.Driver

spring.jpa.database: MYSQL
spring.jpa.show-sql: true
spring.jpa.hibernate.ddl-auto: update
spring.jpa.properties.hibernate.dialect: org.hibernate.dialect.MySQL5Dialect
